name: Daily Netlify Redeploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
